/*Qué son (y para qué sirven) los sistemas de control de versiones y cómo pueden ayudar a nuestro flujo de desarrollo
Nos ayudan a mantener un historial de cambios;
Nos ayudan a tener control sobre cada cambio en el código;
Nos ayudan a que un cambio de una persona no influya en el cambio realizado por otra;
Etc.
Qué es Git y cómo instalarlo
Que con el comando git init pudimos crear un repositorio Git;
Cómo analizar el estado de nuestro repositorio usando el comando git status.*/
 /*Antes de cualquier interacción con git, es necesario informar quién eres para que almacene correctamente los datos del autor de cada uno de los cambios en el código.

Simplemente escribe los siguientes comandos (estando en la carpeta del repositorio de git):

git config --local user.name "Tu nombre aquí"
git config --local user.email "Tu@email.aqui”
La configuración de usuario es una opción que se puede usar para configurar el usuario que se usará para almacenar los cambios en el repositorio.*/
